server:
  port: 8081

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:test@gmail.com}
  password: ${MAIL_OASSWORD:testpassword}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
